### ISSUE TITLE
Consider adding separate budgets and goals

### ISSUE THREAD

**Issue by saintpou** [danilkinkin/buckwheat#113] opened 2024-04-29 09:49 UTC
I can clearly see the simplicity of the app. It makes it more attractive and easier to use. But the option to have multiple, separated budgets would open up the app more, without making it too complicated.

Also, I use the app as a way to set goals for my budget (opposite of the intended usage). It really works great in that way too.
It would be awesome if we could have an option to switch the "budget" to "goal".

**Comment by IMNOTIKE** [comment] 2024-11-07 20:45
Actually I think this is a duplicate of #34 which is already in the project todos. @saintpou consider closing this issue and maybe adding the "goal" part as a comment in that issue

**Comment by saintpou** [comment] 2024-11-14 05:53
> Actually I think this is a duplicate of #34 which is already in the project todos. @saintpou consider closing this issue and maybe adding the "goal" part as a comment in that issue

You're right, don't know how'd I miss that.

**Closed** 2024-11-14 05:53 UTC
Labels: enhancement
