### ISSUE TITLE
Bottom Sheet Opening Multiple time 

### ISSUE THREAD

**Issue by VipulDamor** [danilkinkin/buckwheat#67] opened 2023-07-15 08:00 UTC
**Describe the bug**
Bottom sheet dialog is opening multiple time 

**To Reproduce**
1. on home screen click on 'From Today' budget 
2. Click on 'reset'
3. click out side of bottom sheet dialog 
4. it dismiss multiple time may open multiple time ?

**Expected behavior**
it should open single time like Theme Bottom Sheet 

**Screenshots**
I have recorded video you can find in below google drive link 

[video link](https://drive.google.com/file/d/1-2xFPFq-Sts2ViDhp8X4RSPmoi-RJNIp/view?usp=sharing)

**Comment by danilkinkin** [comment] 2023-07-15 10:12
Thanks, I couldn't reproduce the bug quickly. But I'll try to dig deeper later.

What version of the app do you have? It can be viewed by clicking on the gear icon.

Thanks for the info

**Comment by VipulDamor** [comment] 2023-07-15 10:28
i have checkout your master branch , i ran application in emulator (maybe
🤔 that causing issue )

**Comment by danilkinkin** [comment] 2023-09-02 12:44
Fixed in release [v.3.11.0](https://github.com/danilkinkin/buckwheat/releases/tag/3.11.0)

**Closed by danilkinkin** 2023-09-02 12:44 UTC
Labels: bug
